# Generated by Django 5.0.7 on 2024-09-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foot',
            new_name='Footballers',
        ),
    ]
